"""empty message

Revision ID: 45815fd4adcf
Revises: e599dab4f1d4
Create Date: 2017-02-12 12:52:04.369637

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '45815fd4adcf'
down_revision = 'e599dab4f1d4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_name', sa.String(length=60), nullable=True),
    sa.Column('event_description', sa.String(length=60), nullable=True),
    sa.Column('event_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_event_event_date'), 'event', ['event_date'], unique=False)
    op.create_index(op.f('ix_event_event_description'), 'event', ['event_description'], unique=False)
    op.create_index(op.f('ix_event_event_name'), 'event', ['event_name'], unique=False)
    op.create_table('student',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=60), nullable=True),
    sa.Column('last_name', sa.String(length=60), nullable=True),
    sa.Column('ccid', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_student_ccid'), 'student', ['ccid'], unique=True)
    op.create_index(op.f('ix_student_first_name'), 'student', ['first_name'], unique=False)
    op.create_index(op.f('ix_student_last_name'), 'student', ['last_name'], unique=False)
    op.create_table('attendance',
    sa.Column('event_id', sa.Integer(), nullable=True),
    sa.Column('student_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['event.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('attendance')
    op.drop_index(op.f('ix_student_last_name'), table_name='student')
    op.drop_index(op.f('ix_student_first_name'), table_name='student')
    op.drop_index(op.f('ix_student_ccid'), table_name='student')
    op.drop_table('student')
    op.drop_index(op.f('ix_event_event_name'), table_name='event')
    op.drop_index(op.f('ix_event_event_description'), table_name='event')
    op.drop_index(op.f('ix_event_event_date'), table_name='event')
    op.drop_table('event')
    # ### end Alembic commands ###
