"""empty message

Revision ID: b17a4a62e7e2
Revises: 45815fd4adcf
Create Date: 2017-02-12 12:59:07.717840

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b17a4a62e7e2'
down_revision = '45815fd4adcf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attendance', sa.Column('TF_comment', sa.String(length=1000), nullable=True))
    op.drop_index('ix_event_event_description', table_name='event')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_event_event_description', 'event', ['event_description'], unique=False)
    op.drop_column('attendance', 'TF_comment')
    # ### end Alembic commands ###
